### ISSUE TITLE
快速开始有部分markdown编写错误

### ISSUE THREAD

**Issue by psacal** [MinecraftFunctionPlusPlus/MCFPPAPI#1]
/[docs](https://github.com/MinecraftFunctionPlusPlus/MCFPPAPI/tree/main/docs)/[zh](https://github.com/MinecraftFunctionPlusPlus/MCFPPAPI/tree/main/docs/zh)/[quickstart](https://github.com/MinecraftFunctionPlusPlus/MCFPPAPI/tree/main/docs/zh/quickstart)
/index.md
![捕获](https://github.com/MinecraftFunctionPlusPlus/MCFPPAPI/assets/26455742/2934384d-02a9-4411-b82f-6d316aa4e3db)
在快速开始的说明中有一些提醒未生效，如
:::warning{title=Note!} mcfpp中的类必须以大写字母开头。 :::
其它文档也有，望修复
（issue自seewo一体机）

**Comment by Alumopper** [comment]
修复了喵
